# 1.Purpose of Numpy.random package

       To generate an array of random numbers  we need to use numpy. numpy has the numpy.random package which has multiple 
    functions to generate the random n-dimensional array for various distributions.To generate “true” random numbers, random
    number generators gather random data from the physical world around them. For random numbers that are cannot
    be random, we may just use an algorithm and a seed value.Generating truly random numbers in software is indeed 
    impossible, however it is possible with hardware to build a device which can generate truly random numbers.This package 
    approximate random numbers, but are 100% determined by the input and the pseudo-random number algorithm.
       
 ###       How to select a random number in Python
use range(5) if you want only 5 values returned, etc. Then the code  print random.randint(1,101) will automatically select 
a random integer between 1 and 100 .This code will generate a random number between 1 and 20, and then multiply that number
by 5.
       
  ###     Generating Random Numbers With NumPy
Import Numpy. import numpy as np.
Generate A Random Number From The Normal Distribution. np. random. normal()
Generate Four Random Numbers From The Normal Distribution. np. random. 
Generate Four Random Numbers From The Uniform Distribution. np. random. 
Generate Four Random Integers Between 1 and 100. np. random.

  #### Normal Distribution
A normal distribution is an arrangement of a data set in which most values cluster in the middle of the range and the rest 
taper off symmetrically toward either extreme.A normal distribution is a distribution that is solely dependent on two
parameters of the data set: its mean and the standard deviation of the sample. Mean — This is the average value of all the 
    points in the sample. Standard Deviation — This indicates how much the data set deviates from the mean of the sample.
 

# 2.Use of "Simple random data" and "Permutations" functions
 ### numpy.random.randint
Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low,high)

If high is None (the default), then results are from [0, low).

Parameters:	
low : int

Lowest (signed) integer to be drawn from the distribution (unless high=None, in which case this parameter is one above the
                                                           highest such integer).

high : int, optional

If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None).

size : int or tuple of ints, optional

Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a
single value is returned.

dtype : dtype, optional

Desired dtype of the result. All dtypes are determined by their name, i.e., ‘int64’, ‘int’, etc, so byteorder is not available 
and a specific precision may have different C types depending on the platform. The default value is ‘np.int’.


            
Example :     


   


In [9]:
np.random.randint(2, size=10)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.random.randint(5, size=(2, 4))

array([[2, 3, 2, 3],
       [1, 0, 2, 3]])

#### Permutation
  Permutation is an arrangement of objects in a specific order.The number of permutations on a set of n elements is given by n!
 
 numpy.random.permutation(x)
Randomly permute a sequence, or return a permuted range.

If x is a multi-dimensional array, it is only shuffled along its first index.

Parameters:	
x : int or array_like

If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.

Returns:	
out : ndarray

Permuted sequence or array range.   

In [13]:
np.random.permutation(10)

array([3, 2, 4, 7, 5, 0, 1, 6, 8, 9])

In [14]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 9,  4, 12, 15,  1])

In [15]:
arr = np.arange(9).reshape((3, 3))
 np.random.permutation(arr)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# numpy.random.shuffle
numpy.random.shuffle(x)
Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

Parameters:	
x : array_like

The array or list to be shuffled.


In [20]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([8, 1, 9, 0, 3, 4, 7, 5, 2, 6])

In [21]:
arr = np.arange(9).reshape((3, 3))
 np.random.shuffle(arr)
 arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [ ]:
# 3.Use and Purpose of "Distributions" functions
 
##### numpy.random.normal
numpy.random.normal(loc=0.0, scale=1.0, size=None)
Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution,is often called the bell curve because of its characteristic shape.

Parameters:	
loc : float or array_like of floats

Mean (“centre”) of the distribution.

scale : float or array_like of floats

Standard deviation (spread or “width”) of the distribution.

size : int or tuple of ints, optional

Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default),
a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.

Returns:	
out : ndarray or scalar

The probability density for the Gaussian distribution is
$ p(x) = \frac{1}{\sqrt{ 2 \pi \sigma^2 }}
e^{ - \frac{ (x - \mu)^2 } {2 \sigma^2} }  $

where  $ \mu $ is the mean and $\sigma$ the standard deviation. The square of the standard deviation, $\sigma^2$, is called the variance.

The function has its peak at the mean, and its “spread” increases with the standard deviation (the function reaches 0.607 times its maximum at $x + \sigma$ and $x- \sigma$ .


In [7]:
import numpy as np
mu, sigma = 0, 0.1   # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)   

%matplotlib inline
import matplotlib.pyplot as plt
count, bins, ignored = plt.hist(s, 30, normed=True)

 plt.plot( bins, 1 / (sigma * np.sqrt(2 * np.pi)) *
...                np.exp( - (bins - mu)**2 / (2 * sigma**2) ),
...          linewidth=2, color='r')
 plt.show()